### ISSUE TITLE
[BUG] [FORGE] Crash on load in `RegisterCommandsEvent`

### ISSUE THREAD

**Issue by egelja** [quat1024/incorporeal-3#11]
Crash report and `latest.log` attached, but main issue seems to be 
```
java.lang.IllegalArgumentException: Listener for event class net.minecraftforge.event.RegisterCommandsEvent takes an argument that is not a subtype of the base type interface net.minecraftforge.fml.event.IModBusEvent
    ...
    at agency.highlysuspect.incorporeal.platform.forge.IncBootstrapForge.registerCommands(IncBootstrapForge.java:149)
```

[crash-2022-06-08_09.19.56-fml.txt](https://github.com/quat1024/incorporeal-3/files/8862527/crash-2022-06-08_09.19.56-fml.txt)
[latest.log](https://github.com/quat1024/incorporeal-3/files/8862602/latest.log)
---
Thank you very much!

**Comment by quat1024** [comment]
I may be stupid lol

**Comment by quat1024** [comment]
Pushed a version 3 on modrinth & curseforge just for forge, i didnt push a version 3 for fabric because it wasn't broken.
