### ISSUE TITLE
Blood Soul Core crashes game on rightclick

### ISSUE THREAD

**Issue by Gronglegrowth** [quat1024/incorporeal-3#14]
This crash mentions optifine because the player who reported it to me initially used it, but a player without optifine also tested and it resulted in the same crash. Crashreport is attached.

[crash-2022-08-03_15.26.58-client.txt](https://github.com/quat1024/incorporeal-3/files/9251760/crash-2022-08-03_15.26.58-client.txt)

**Comment by quat1024** [comment]
Sorry for taking so long to get to this, was busy with other projects.

```
java.lang.NoSuchMethodError: 'boolean vazkii.botania.common.helper.PlayerHelper.isTruePlayer(net.minecraft.world.entity.Entity)'
	at agency.highlysuspect.incorporeal.block.SoulCoreBlock.m_6227_(SoulCoreBlock.java:53) ~[Incorporeal-3-forge-1.18.2-4.jar%2387!/:?] {re:classloading}
```

This looks like the exact opposite of https://github.com/quat1024/incorporeal-3/issues/12 . Botania v434 moved a method I was borrowing from `EntityDoppleganger` to `PlayerHelper`, and v4 of this mod made the corresponding change on my side. So if you update Incorporeal to v4 you have to update Botania as well. You should update Botania anyways cause it has some good changes :]

I don't know if it's possible to make the usual "mod `blah ` expects version `whatever` of mod `blahblah`" screen pop up with Botania. Modloader version constraints are usually expressed with semantic version numbers, but Botania has a weird version numbering scheme which isn't comparable
