### ISSUE TITLE
figure out why floating flower items are broked on fabric

### ISSUE THREAD

**Issue by quat1024** [quat1024/incorporeal-3#4]
the botania ones work ok its just mine that are broken

(if it's mod load order related im gonna hoot and holler)

**Comment by williewillus** [comment]
Using `parent` for the item models doesn't work anymore because reasons tm, just repeat the block model into the item model json. Botania example: https://github.com/VazkiiMods/Botania/blob/1.18.x/Xplat/src/generated/resources/assets/botania/models/item/floating_bubbell.json
